---
name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout gomega-lint
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: run unit tests
        run: |
          go version
          make test
...
